import { contextBridge, ipcRenderer, webUtils, type IpcRendererEvent } from 'electron'
import type { ExcelSyncBridge } from '../shared/contracts'

const bridge: ExcelSyncBridge = {
  authState: () => ipcRenderer.invoke('auth:state'),
  bootstrap: (username, password, setupCode) => ipcRenderer.invoke('auth:bootstrap', username, password, setupCode),
  login: (username, password) => ipcRenderer.invoke('auth:login', username, password),
  activateInvite: (code, password) => ipcRenderer.invoke('auth:activateInvite', code, password),
  logout: () => ipcRenderer.invoke('auth:logout'),
  devices: () => ipcRenderer.invoke('auth:devices'),
  logoutDevice: (deviceId) => ipcRenderer.invoke('auth:logoutDevice', deviceId),
  logoutOtherDevices: () => ipcRenderer.invoke('auth:logoutOtherDevices'),
  logoutAllDevices: () => ipcRenderer.invoke('auth:logoutAllDevices'),
  dashboard: () => ipcRenderer.invoke('dashboard:get'),
  files: () => ipcRenderer.invoke('files:list'),
  trash: () => ipcRenderer.invoke('trash:list'),
  activity: () => ipcRenderer.invoke('activity:list'),
  notifications: (filter) => ipcRenderer.invoke('notifications:list', filter ?? 'all'),
  markNotificationRead: (notificationId) => ipcRenderer.invoke('notifications:read', notificationId),
  markAllNotificationsRead: () => ipcRenderer.invoke('notifications:readAll'),
  advancedSearch: (input) => ipcRenderer.invoke('search:advanced', input),
  pending: () => ipcRenderer.invoke('pending:list'),
  problems: () => ipcRenderer.invoke('pending:problems'),
  versions: (fileId) => ipcRenderer.invoke('versions:list', fileId),
  previewVersion: (fileId, version, sheetName) => ipcRenderer.invoke('versions:preview', fileId, version, sheetName),
  downloadVersion: (fileId, version) => ipcRenderer.invoke('versions:download', fileId, version),
  openVersionCopy: (fileId, version) => ipcRenderer.invoke('versions:openCopy', fileId, version),
  restore: (fileId, version) => ipcRenderer.invoke('versions:restore', fileId, version),
  compareVersions: (fileId, fromVersion, toVersion) => ipcRenderer.invoke('versions:compare', fileId, fromVersion, toVersion),
  fileLease: (fileId) => ipcRenderer.invoke('fileLease:get', fileId),
  requestFileLeaseTakeover: (fileId) => ipcRenderer.invoke('fileLease:requestTakeover', fileId),
  forceFileLeaseTakeover: (fileId) => ipcRenderer.invoke('fileLease:forceTakeover', fileId),
  comments: (fileId) => ipcRenderer.invoke('comments:list', fileId),
  createComment: (fileId, input) => ipcRenderer.invoke('comments:create', fileId, input),
  resolveComment: (commentId, reopen) => ipcRenderer.invoke('comments:resolve', commentId, reopen ?? false),
  rewindPreview: (input) => ipcRenderer.invoke('rewind:preview', input),
  executeRewind: (input) => ipcRenderer.invoke('rewind:execute', input),
  rewindHistory: (workspaceId) => ipcRenderer.invoke('rewind:history', workspaceId),
  retryRewind: (operationId) => ipcRenderer.invoke('rewind:retry', operationId),
  activeLocks: () => ipcRenderer.invoke('admin:activeLocks'),
  restoreLocalCopy: (fileId) => ipcRenderer.invoke('files:restoreLocal', fileId),
  trashFile: (fileId) => ipcRenderer.invoke('files:trash', fileId),
  restoreTrash: (fileId) => ipcRenderer.invoke('trash:restore', fileId),
  permanentlyDelete: (fileId) => ipcRenderer.invoke('trash:permanentDelete', fileId),
  openFile: (fileId) => ipcRenderer.invoke('files:open', fileId),
  setFileFavorite: (fileId, favorite) => ipcRenderer.invoke('files:favorite', fileId, favorite),
  previewFile: (fileId, sheetName) => ipcRenderer.invoke('files:preview', fileId, sheetName),
  downloadFile: (fileId) => ipcRenderer.invoke('files:download', fileId),
  downloadFiles: (fileIds) => ipcRenderer.invoke('files:downloadMany', fileIds),
  renameFile: (fileId, newName) => ipcRenderer.invoke('files:rename', fileId, newName),
  moveFile: (fileId, newRelativePath) => ipcRenderer.invoke('files:move', fileId, newRelativePath),
  copyFile: (fileId) => ipcRenderer.invoke('files:copy', fileId),
  createFolder: (relativeParent, folderName) => ipcRenderer.invoke('files:createFolder', relativeParent, folderName),
  retryTask: (taskId) => ipcRenderer.invoke('pending:retry', taskId),
  cancelTask: (taskId) => ipcRenderer.invoke('pending:cancel', taskId),
  resolveConflict: (fileId, choice) => ipcRenderer.invoke('conflict:resolve', fileId, choice),
  importExcelFiles: (storageBackend) => ipcRenderer.invoke('files:import', storageBackend),
  importExcelFolder: (storageBackend) => ipcRenderer.invoke('files:importFolder', storageBackend),
  importDroppedFiles: (files, storageBackend) => ipcRenderer.invoke('files:importPaths', files.map((file) => webUtils.getPathForFile(file)).filter(Boolean), storageBackend),
  selectSyncDirectory: () => ipcRenderer.invoke('settings:selectDirectory'),
  openSyncDirectory: () => ipcRenderer.invoke('settings:openDirectory'),
  settings: () => ipcRenderer.invoke('settings:get'),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  telegramUserStatus: () => ipcRenderer.invoke('telegramUser:status'),
  beginTelegramUserAuth: (phone) => ipcRenderer.invoke('telegramUser:beginAuth', phone),
  submitTelegramUserCode: (code) => ipcRenderer.invoke('telegramUser:submitCode', code),
  submitTelegramUserPassword: (password) => ipcRenderer.invoke('telegramUser:submitPassword', password),
  syncTelegramUserGroup: () => ipcRenderer.invoke('telegramUser:sync'),
  reauthorizeTelegramUser: () => ipcRenderer.invoke('telegramUser:reauthorize'),
  restartTelegramUserAuth: () => ipcRenderer.invoke('telegramUser:restartAuth'),
  syncNow: () => ipcRenderer.invoke('sync:now'),
  pauseSync: (paused) => ipcRenderer.invoke('sync:pause', paused),
  workspaces: () => ipcRenderer.invoke('workspace:list'),
  setDefaultWorkspace: (workspaceId) => ipcRenderer.invoke('workspace:setDefault', workspaceId),
  workspaceMembers: (workspaceId) => ipcRenderer.invoke('workspace:members', workspaceId),
  saveWorkspaceMember: (workspaceId, userId, role) => ipcRenderer.invoke('workspace:saveMember', workspaceId, userId, role),
  removeWorkspaceMember: (workspaceId, userId) => ipcRenderer.invoke('workspace:removeMember', workspaceId, userId),
  createWorkspace: (input) => ipcRenderer.invoke('workspace:create', input),
  archiveWorkspace: (workspaceId) => ipcRenderer.invoke('workspace:archive', workspaceId),
  setWorkspaceStorage: (workspaceId, storageConnectionId) => ipcRenderer.invoke('workspace:setStorage', workspaceId, storageConnectionId),
  resourceAccess: (workspaceId, userId) => ipcRenderer.invoke('workspace:resourceAccess', workspaceId, userId),
  replaceResourceAccess: (workspaceId, userId, input) => ipcRenderer.invoke('workspace:replaceResourceAccess', workspaceId, userId, input),
  tasks: (scope, workspaceId) => ipcRenderer.invoke('userTasks:list', scope, workspaceId),
  createUserTask: (input) => ipcRenderer.invoke('userTasks:create', input),
  updateUserTask: (taskId, input) => ipcRenderer.invoke('userTasks:update', taskId, input),
  deleteUserTask: (taskId) => ipcRenderer.invoke('userTasks:delete', taskId),
  migrateLocalTasks: (tasks) => ipcRenderer.invoke('userTasks:migrateLocal', tasks),
  adminUsers: () => ipcRenderer.invoke('admin:users'),
  adminUserDevices: (userId) => ipcRenderer.invoke('admin:userDevices', userId),
  adminInvites: () => ipcRenderer.invoke('admin:invites'),
  createInvite: (input) => ipcRenderer.invoke('admin:createInvite', input),
  revokeInvite: (inviteId) => ipcRenderer.invoke('admin:revokeInvite', inviteId),
  regenerateInvite: (inviteId) => ipcRenderer.invoke('admin:regenerateInvite', inviteId),
  setUserLifecycle: (userId, status, reassignToUserId) => ipcRenderer.invoke('admin:setUserLifecycle', userId, status, reassignToUserId),
  forceLogoutUser: (userId) => ipcRenderer.invoke('admin:forceLogoutUser', userId),
  setUserSystemRole: (userId, systemRole) => ipcRenderer.invoke('admin:setUserSystemRole', userId, systemRole),
  setUserAccountPolicy: (userId, accountType, accessExpiresAt) => ipcRenderer.invoke('admin:setUserAccountPolicy', userId, accountType, accessExpiresAt),
  groups: () => ipcRenderer.invoke('admin:groups'),
  createGroup: (name) => ipcRenderer.invoke('admin:createGroup', name),
  archiveGroup: (groupId) => ipcRenderer.invoke('admin:archiveGroup', groupId),
  groupMembers: (groupId) => ipcRenderer.invoke('admin:groupMembers', groupId),
  replaceGroupMembers: (groupId, userIds) => ipcRenderer.invoke('admin:replaceGroupMembers', groupId, userIds),
  groupResourceAccess: (workspaceId, groupId) => ipcRenderer.invoke('admin:groupResourceAccess', workspaceId, groupId),
  replaceGroupResourceAccess: (workspaceId, groupId, input) => ipcRenderer.invoke('admin:replaceGroupResourceAccess', workspaceId, groupId, input),
  storageConnections: () => ipcRenderer.invoke('admin:storageConnections'),
  createStorageConnection: (name, botToken) => ipcRenderer.invoke('admin:createStorageConnection', name, botToken),
  rotateStorageToken: (storageId, botToken) => ipcRenderer.invoke('admin:rotateStorageToken', storageId, botToken),
  startStoragePair: (storageId) => ipcRenderer.invoke('admin:startStoragePair', storageId),
  confirmStoragePair: (storageId) => ipcRenderer.invoke('admin:confirmStoragePair', storageId),
  disableStorageConnection: (storageId) => ipcRenderer.invoke('admin:disableStorageConnection', storageId),
  checkStorageHealth: () => ipcRenderer.invoke('admin:checkStorageHealth'),
  auditLogs: () => ipcRenderer.invoke('admin:auditLogs'),
  systemStatus: () => ipcRenderer.invoke('admin:systemStatus'),
  versionIntegrity: () => ipcRenderer.invoke('admin:versionIntegrity'),
  repairVersionIntegrity: (fileId) => ipcRenderer.invoke('admin:repairVersionIntegrity', fileId),
  filePresence: (fileId) => ipcRenderer.invoke('presence:get', fileId),
  setFilePresence: (fileId, state) => ipcRenderer.invoke('presence:set', fileId, state),
  clearFilePresence: (fileId) => ipcRenderer.invoke('presence:clear', fileId),
  clientVersion: () => ipcRenderer.invoke('client:version'),
  storageStatus: () => ipcRenderer.invoke('storage:status'),
  startTelegramPair: () => ipcRenderer.invoke('storage:pairStart'),
  confirmTelegramPair: () => ipcRenderer.invoke('storage:pairConfirm'),
  openTelegramPairLink: (url) => ipcRenderer.invoke('storage:openPairLink', url),
  onStateChanged: (callback) => {
    const listener = (): void => callback()
    ipcRenderer.on('state:changed', listener)
    return () => ipcRenderer.removeListener('state:changed', listener)
  },
  onTransferProgress: (callback) => {
    const listener = (_event: IpcRendererEvent, progress: Parameters<typeof callback>[0]): void => callback(progress)
    ipcRenderer.on('transfer:progress', listener)
    return () => ipcRenderer.removeListener('transfer:progress', listener)
  },
  onAuthChanged: (callback) => {
    const listener = (): void => callback()
    ipcRenderer.on('auth:changed', listener)
    return () => ipcRenderer.removeListener('auth:changed', listener)
  }
}

contextBridge.exposeInMainWorld('excelSync', bridge)
